apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-hello
      tier: frontend
  template:
    metadata:
      labels:
        app: flask-hello
        tier: frontend
    spec:
      containers:
        - name: flask-hello
          image: vrindabs/flask-hello-k8s:latest
          ports:
            - containerPort: 5000
