apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service-nodeport
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  selector:
    app: flask-hello
    tier: frontend
